name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: e.g., The dashboard fails to load when uploading video files
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. See error
      placeholder: |
        1. Navigate to the dashboard
        2. Click on "Upload Video"
        3. Select a video file
        4. Error occurs
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Your Python version (e.g., 3.10.0)
      placeholder: 3.10.0
  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Your OS (e.g., Windows 11, Ubuntu 22.04)
      placeholder: Windows 11
  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please include any relevant log output here.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/yourusername/TrafficAI/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
