name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!
  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: A clear and concise name for the feature.
      placeholder: e.g., Detailed Violation Reports
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Statement
      description: |
        Describe the problem this feature would solve.
        What is the current limitation?
      placeholder: |
        Currently, the system only shows basic violation information.
        Users need more detailed reports with analytics and export options.
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your proposed solution.
        How should the feature work?
      placeholder: |
        Add a new "Reports" section with:
        - Export to PDF/CSV
        - Date range filtering
        - Statistical analytics
        - Charts and graphs
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/yourusername/TrafficAI/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
