"""Fresh init

Revision ID: 89e5ebe0580e
Revises: 
Create Date: 2026-01-26 18:48:10.494369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e5ebe0580e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('license_plate', sa.String(length=20), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('signal_state', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_license_plate'), ['license_plate'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_violation_type'), ['violation_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_violation_type'))
        batch_op.drop_index(batch_op.f('ix_violations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_violations_license_plate'))

    op.drop_table('violations')
    # ### end Alembic commands ###
