"""extend_schema_and_sync_violation

Revision ID: f6bfb8f7c201
Revises: 89e5ebe0580e
Create Date: 2026-02-08 18:10:12.219439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bfb8f7c201'
down_revision = '89e5ebe0580e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stream_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('traffic_officers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_name', sa.String(length=100), nullable=False),
    sa.Column('badge_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('traffic_officers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_officers_badge_number'), ['badge_number'], unique=True)

    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], name='fk_vehicle_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_license_plate'), ['license_plate'], unique=True)

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('camera_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('officer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frame_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_fps', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('video_path', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_violation_vehicle', 'vehicles', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('fk_violation_camera', 'cameras', ['camera_id'], ['id'])
        batch_op.create_foreign_key('fk_violation_officer', 'traffic_officers', ['officer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_constraint('fk_violation_officer', type_='foreignkey')
        batch_op.drop_constraint('fk_violation_camera', type_='foreignkey')
        batch_op.drop_constraint('fk_violation_vehicle', type_='foreignkey')
        batch_op.drop_column('video_path')
        batch_op.drop_column('video_fps')
        batch_op.drop_column('frame_number')
        batch_op.drop_column('officer_id')
        batch_op.drop_column('camera_id')
        batch_op.drop_column('vehicle_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_license_plate'))

    op.drop_table('vehicles')
    with op.batch_alter_table('traffic_officers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_officers_badge_number'))

    op.drop_table('traffic_officers')
    op.drop_table('owners')
    op.drop_table('cameras')
    # ### end Alembic commands ###
